In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)
a.ndim

[1 2 3 4]


1

In [4]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
a.ndim

[[1 2 3 4]
 [5 6 7 8]]


2

In [5]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
a.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

In [8]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


## arange()

In [9]:
import numpy as np

In [10]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [11]:
a=np.arange(1,25,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [12]:
a=np.arange(1,35,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [13]:
a=np.arange(1,35,3)
a

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34])

In [16]:
a=np.arange(1,30,3)
a

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [19]:
## Using data type
a=np.arange(1,20,2,dtype=int)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [20]:
## Using data type
a=np.arange(1,30,2,dtype=float)
print(a)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29.]


In [21]:
a=np.arange(1,10,2,dtype=float)
print(a)

[1. 3. 5. 7. 9.]


## linspace

In [22]:
import numpy as np

In [23]:
a=np.linspace(10,20,6)
print(a)

[10. 12. 14. 16. 18. 20.]


In [24]:
a=np.linspace(10,20,5)
print(a)

[10.  12.5 15.  17.5 20. ]


In [27]:
a=np.linspace(10,20,6)
print(a)

[10. 12. 14. 16. 18. 20.]


In [28]:
a=np.linspace(10,100,10)
print(a)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


## zeros

In [29]:
a=np.zeros([3,3],dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [30]:
a=np.zeros([5,5],dtype=int)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [31]:
a=np.zeros([6,6],dtype=float)
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


### Ones

In [32]:
a=np.ones([3,3],dtype=int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [33]:
a=np.ones([3,3],dtype=float)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
a=np.ones([4,4],dtype=int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [35]:
import numpy as np 

In [37]:
a=np.arange(1,11)
print(a)
print()
print(a.ndim)

[ 1  2  3  4  5  6  7  8  9 10]

1


In [38]:
a=np.arange(1,61)
print(a)
print()
print(a.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]

1


In [39]:
a=np.arange(1,61)
print(a)
print()
print('Before=',a.ndim)
print('______________')



b=np.arange(61,121).reshape(10,6)
print(b)
print()
print('After=',b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]

Before= 1
______________
[[ 61  62  63  64  65  66]
 [ 67  68  69  70  71  72]
 [ 73  74  75  76  77  78]
 [ 79  80  81  82  83  84]
 [ 85  86  87  88  89  90]
 [ 91  92  93  94  95  96]
 [ 97  98  99 100 101 102]
 [103 104 105 106 107 108]
 [109 110 111 112 113 114]
 [115 116 117 118 119 120]]

After= 2


In [44]:
a=np.arange(1,61)
print(a)
print()
print('Before=',a.ndim)

b=np.arange(1,61).reshape(10,6)
print(b)
print()
print('After=',b.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]

Before= 1
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]

After= 2


In [45]:
b[5][4]

35

In [46]:
b[5][0]

31

In [48]:
b[0][4]

5

In [49]:
b[4][3]

28

In [50]:
a=np.arange(1,61).reshape(5,2,6)
print(a)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]


In [53]:
a[4][1][0]

55

In [54]:
a[4][1][3]

58

In [61]:
import numpy as np

In [62]:
a=np.arange(1,61).reshape(10,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]


In [65]:
np.sum(a,axis=0)

array([280, 290, 300, 310, 320, 330])

In [66]:
np.sum(a,axis = 0)   # 0 -> means columns for numpy

array([280, 290, 300, 310, 320, 330])

In [67]:
np.sum(a,axis=1)

array([ 21,  57,  93, 129, 165, 201, 237, 273, 309, 345])

In [68]:
np.sum(a)

1830

In [69]:
## random functions

In [75]:
np.random.randint(10,50)

15

In [76]:
np.random.rand(3,4)

array([[0.80464789, 0.75918379, 0.03007942, 0.88056933],
       [0.43608871, 0.32578713, 0.10983292, 0.54272792],
       [0.39140097, 0.15105159, 0.1973993 , 0.54047304]])

In [77]:
np.random.randn(3,4)

array([[-1.9831831 , -0.19675613, -0.4093983 , -0.57636286],
       [-0.17605847,  1.06794463,  0.04071412,  1.61380272],
       [-0.46248939,  0.65551039,  0.20680241, -0.64012103]])

In [81]:
np.random.random((5,4))

array([[0.69932657, 0.53992347, 0.37659518, 0.97636069],
       [0.72737216, 0.37117486, 0.55716706, 0.35513216],
       [0.86813952, 0.23811328, 0.28337074, 0.14045451],
       [0.8354598 , 0.19613001, 0.07406747, 0.56696983],
       [0.70649186, 0.89069945, 0.02852093, 0.67959162]])

In [84]:
np.sqrt(18)

4.242640687119285

In [85]:
np.sqrt(16)

4.0

In [86]:
## concatenate

In [99]:
a=np.array([[1,2,3],[4,5,6,]])
b=np.array([[10,11,12],[13,14,15]])
print(a)
print()
print(b)
c=np.concatenate((a,b))
print(c)

[[1 2 3]
 [4 5 6]]

[[10 11 12]
 [13 14 15]]
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [13 14 15]]


In [90]:
c=np.concatenate((a,b))
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [13 14 15]]


In [96]:
import numpy as np

In [100]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print(a)
print()
print(b)
c=np.concatenate((a,b))
print(c)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Vstack and hstack

In [104]:
## Vstack ---> Vertical 
# hstack
a=np.arange(1,61).reshape(10,6)
print(a)
b=np.arange(61,121).reshape(10,6)
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
[[ 61  62  63  64  65  66]
 [ 67  68  69  70  71  72]
 [ 73  74  75  76  77  78]
 [ 79  80  81  82  83  84]
 [ 85  86  87  88  89  90]
 [ 91  92  93  94  95  96]
 [ 97  98  99 100 101 102]
 [103 104 105 106 107 108]
 [109 110 111 112 113 114]
 [115 116 117 118 119 120]]


In [106]:
vstack=np.vstack((a,b))
vstack

array([[  1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18],
       [ 19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36],
       [ 37,  38,  39,  40,  41,  42],
       [ 43,  44,  45,  46,  47,  48],
       [ 49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66],
       [ 67,  68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78],
       [ 79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96],
       [ 97,  98,  99, 100, 101, 102],
       [103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119, 120]])

In [108]:
hstack=np.hstack((a,b))
hstack

array([[  1,   2,   3,   4,   5,   6,  61,  62,  63,  64,  65,  66],
       [  7,   8,   9,  10,  11,  12,  67,  68,  69,  70,  71,  72],
       [ 13,  14,  15,  16,  17,  18,  73,  74,  75,  76,  77,  78],
       [ 19,  20,  21,  22,  23,  24,  79,  80,  81,  82,  83,  84],
       [ 25,  26,  27,  28,  29,  30,  85,  86,  87,  88,  89,  90],
       [ 31,  32,  33,  34,  35,  36,  91,  92,  93,  94,  95,  96],
       [ 37,  38,  39,  40,  41,  42,  97,  98,  99, 100, 101, 102],
       [ 43,  44,  45,  46,  47,  48, 103, 104, 105, 106, 107, 108],
       [ 49,  50,  51,  52,  53,  54, 109, 110, 111, 112, 113, 114],
       [ 55,  56,  57,  58,  59,  60, 115, 116, 117, 118, 119, 120]])

In [109]:
a=[1,2,3,4]
np.sum(a)

10

In [110]:
np.max(a)

4

In [111]:
np.min(a)

1

In [112]:
a=np.diag([1,2,3,4,5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [113]:
## ravel

In [114]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
2


In [115]:
b=a.ravel()
print(b)
print(b.ndim)

[1 2 3 4 5 6]
1


In [116]:
## Traspose matrix

In [117]:
t=np.array([[1,2,3],[4,5,6]])
print(t)
print(t.ndim)

[[1 2 3]
 [4 5 6]]
2


In [118]:
t.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [119]:
# Abs absloute value

In [120]:
a=np.abs(-130)
print(a)

130


In [121]:
a=np.abs(-150)
print(a)

150


In [122]:
## Eye means diagonal

In [123]:
a=np.eye(6,6,dtype=int)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [124]:
a=np.eye(5,5,dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
